### ISSUE TITLE
发现一处代码逻辑的不严谨

### ISSUE THREAD

**Issue by CodeSlaveZhang** [imdong/UoocAutoLearn#6]
`UoocAutoLearn.getUnitLearn = function () {
        $.ajax({
            type: "GET",
            url: '/home/learn/getUnitLearn',
            data: {
                cid: this.cid,
                chapter_id: this.chapter_id,
                section_id: this.section_id,
                catalog_id: this.catalog_id
            },
            success: function (response) {
                // 遍历每一个视频
                var isFinished = true;
                for (let index = 0; index < response.data.length; index++) {
                    const item = response.data[index];
                    if (item.finished == 0) {
                        UoocAutoLearn.video_pos = parseFloat(item.video_pos);
                        UoocAutoLearn.videoSource = item.video_play_list[0].source;
                        UoocAutoLearn.title = item.title;
                        UoocAutoLearn.resource_id = item.id;
                        isFinished = false;

                        console.log('当前任务', UoocAutoLearn.parent_name, UoocAutoLearn.title);

                        // 获取视频时长
                        UoocAutoLearn.getVideoLength();

                        break;
                    }
                }
                // 如果都看完了
                if (isFinished) {
                    // 获取下一节课
                    UoocAutoLearn.getCatalogList();
                }
            }
        });
    };`
其中：
`                        UoocAutoLearn.videoSource = item.video_play_list[0].source;
`
`item.video_play_list[0]. `可能是空对象，你因该在这里遍历获取第一个视频对象而不是直接取第0个

**Comment by Yunnathai** [comment]
你可以正常用么？为什么不能倍速
